language: ruby
services:
- docker
env:
  global:
  - DEST_ID=core
  - NSVER=7
  - DOCKER_IMAGE=nethserver/makerpms:devtoolset${NSVER}
  - YUM_ARGS=--enablerepo=nethserver-testing
  - >
    EVARS="
    -e DEST_ID -e TRAVIS_BRANCH -e TRAVIS_BUILD_ID -e TRAVIS_PULL_REQUEST_BRANCH
    -e TRAVIS_PULL_REQUEST -e TRAVIS_REPO_SLUG -e TRAVIS_TAG -e NSVER -e VERSIONS_PACK
    -e STAGES_PACK -e YUM_ARGS"

script: >
    docker run --cap-add SYS_PTRACE -ti --name makerpms ${EVARS}
    --hostname "b${TRAVIS_BUILD_NUMBER}.nethserver.org"
    --volume $PWD:/srv/makerpms/src:ro ${DOCKER_IMAGE} makerpms-travis janus-gateway.spec
    && docker cp makerpms:/srv/makerpms/rpmbuild rpmbuild 
    && find rpmbuild



